### PR TITLE
Adds minimal frontend in Preact

### PR DESCRIPTION
**Pull request by aswathkk**
Adds a simple frontend. The overall architecture needs to be reviewed.
Then we will work on minor issues.

### CODE REVIEW

**Comment by kmjayadeep** [comment]
Commit your package-lock.json also

**Review by kmjayadeep — CHANGES_REQUESTED** [review]
Commit package-lock.json
Use the same eslint rules which are used in server side. Make sure they are passing. Otherwise travis build will fail.

**Comment by kmjayadeep** [comment]
npm audit is throwing some security error. take a look into that also

**Comment by aswathkk** [comment]
I installed packages using yarn
Should I install using `npm` and commit package-lock.json??
Or should I commit yarn.lock?

**Comment by kmjayadeep** [comment]
i think we should stick to one package manager. Do npm install once and commit the package-lock. Do not push yarn.lock

**Comment by kmjayadeep** [comment]
Please do a rebase once. Travis CI is ready. It'll show the build status here once you rebase

**Comment by aswathkk** [comment]
ESLint is not configured for JSX and preact.
I will add it as a separate issue.

**Review by kmjayadeep — APPROVED** [review]

**Pull request merged**
