### PR TITLE
Added webpack, babel and configured ssr

### PR DESCRIPTION
**Pull request by kmjayadeep**
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

### CODE REVIEW

**Comment by kmjayadeep** [comment]
CSS is not working with babel and webpack. We may need to change to external stylesheet

**Comment by kmjayadeep** [comment]
@aswathkk It is ready to merge now

**Comment by kmjayadeep** [comment]
lint issues fixed, build passing. Closes #26

**Review by aswathkk — APPROVED** [review]
LGTM.

**Pull request merged**
